### ISSUE TITLE
BUG: Make sure the root name textbox in RegressionVisualization is not requiring a certain name structure

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/ShapeRegressionExtension#17]
It should not need to use "_final_time", just have a numeric sufix that can be used to build the sequence.
<img width="743" alt="screen shot 2018-09-06 at 6 08 31 am" src="https://user-images.githubusercontent.com/2599368/45151164-91dc9600-b19b-11e8-9d31-95af4ff95157.png">
It is certainly true that if you use RegressionComputation that will be the filename, but if you happen to compile the code and run the regression commanline and then want to visualize in SALT, this will not work.

**Comment by bpaniagua** [comment]
I enforce the required rootname, and I still get this message:
`slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'heart_expansion_contraction_final_time_01'
Traceback (most recent call last):
  File "/work/Projects/slicerSALT/SlicerSALT-4.9.0-2018-08-28-linux-amd64/bin/../lib/SlicerSALT-4.9/qt-scripted-modules/RegressionVisualization.py", line 333, in onSequenceCreation
    self.loadModels()
  File "/work/Projects/slicerSALT/SlicerSALT-4.9.0-2018-08-28-linux-amd64/bin/../lib/SlicerSALT-4.9/qt-scripted-modules/RegressionVisualization.py", line 358, in loadModels
    model = MRMLUtility.loadMRMLNode(shapeRootname, inputDirectory, shapeBasename, 'ModelFile')
  File "/work/Projects/slicerSALT/SlicerSALT-4.9.0-2018-08-28-linux-amd64/lib/SlicerSALT-4.9/qt-scripted-modules/ShapeRegressionUtilities/utility.py", line 16, in loadMRMLNode
    node = slicer.util.getNode(node_name)
  File "/work/Projects/slicerSALT/SlicerSALT-4.9.0-2018-08-28-linux-amd64/bin/Python/slicer/util.py", line 666, in getNode
    raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (type(pattern) == str) else ""))
slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'heart_expansion_contraction_final_time_01'`

**Comment by jamesfishbaugh** [comment]
@bpaniagua I agree, I also don't like the way a user has to type a rootname in order to load the sequence. But it isn't as simple as giving just the very beginning of the rootname, since regression also saves intermediate sequences during optimization, which will have the same rootname. 

I made it simpler by searching for any files with *final_time* and automatically populating the rootname box. But that still isn't satisfactory.

I think the best and most elegant solution is the file selection in Paraview. It shows files already collapsed in sequences, so a user can easily choose an entire unique sequence without having to type anything.

![paraview_fileselection](https://user-images.githubusercontent.com/12160522/45178446-afcde900-b1e3-11e8-885f-9b0fa4935499.png)

**Comment by phcerdan** [comment]
We could probably pinch that code from paraview, I will take a look.
