### ISSUE TITLE
IO failing in RegressionVisualization

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/ShapeRegressionExtension#7]
With Qt5

```
Traceback (most recent call last):
  File "/home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build/ShapeRegressionExtension-build/lib/SlicerSALT-4.9/qt-scripted-modules/RegressionVisualization.py", line 370, in onSequenceCreation
    self.loadModels()
  File "/home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build/ShapeRegressionExtension-build/lib/SlicerSALT-4.9/qt-scripted-modules/RegressionVisualization.py", line 396, in loadModels
    model = MRMLUtility.loadMRMLNode(shapeRootname, inputDirectory, shapeBasename, 'ModelFile')
  File "/home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build/ShapeRegressionExtension-build/lib/SlicerSALT-4.9/qt-scripted-modules/ShapeRegressionUtilities/utility.py", line 16, in loadMRMLNode
    node = slicer.util.getNode(node_name)
  File "/home/user/Software/Shape/SALT/buildRelWithDebInfo/Slicer-build/bin/Python/slicer/util.py", line 656, in getNode
    raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (type(pattern) == str) else ""))
slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'Regression_output_final_time_000'
```

**Comment by phcerdan** [comment]
Fixed in #8 #9
